#
version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    # Do not use the .env file here, otherwise the MongoDB container
    # will have access to all the variables stored within the file.
    environment:
      - MONGO_INITDB_ROOT_USERNAME=backenduser
      - MONGO_INITDB_ROOT_PASSWORD=mySuperS3cureP!ssw0rdWhichIsReallyLong
    # Exposing the port is only needed while developing in a local
    # setup. By using the entire docker-compose stack, the database
    # will be linked to the RESTful API directly.
    ports:
      - 27017:27017
  
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass mySuperS3cureP!ssw0rdWhichIsReallyLong
    ports:
      - 6379:6379