#
version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    # Exposing the port is only needed while developing in a local
    # setup. By using the entire docker-compose stack, the database
    # will be linked to the RESTful API directly.
    ports:
      - 27017:27017